### ISSUE TITLE
`get_block_number` always returns `0` inside the contract

### ISSUE THREAD

**Issue by archseer** [Shard-Labs/starknet-devnet#210]

**Comment by archseer** [comment]
I'm guessing this might be because a block has no number on creation: 

https://github.com/Shard-Labs/starknet-devnet/blob/7aa1ff74349cd3c50d731ea415d35b7994cbdc78/starknet_devnet/transactions.py#L40

Until `set_block` is called https://github.com/Shard-Labs/starknet-devnet/blob/7aa1ff74349cd3c50d731ea415d35b7994cbdc78/starknet_devnet/transactions.py#L88-L90

But this happens only after the transaction is executed?

https://github.com/Shard-Labs/starknet-devnet/blob/7aa1ff74349cd3c50d731ea415d35b7994cbdc78/starknet_devnet/starknet_wrapper.py#L150-L172

**Comment by tabaktoni** [comment]
This PR should fix the problem https://github.com/Shard-Labs/starknet-devnet/pull/189
If not we will need more details to reproduce

**Comment by archseer** [comment]
Hmm I tried to test this out by specifying `git+https://github.com/Shard-Labs/starknet-devnet@7d95ac2e66a71664c0c8b750982e73c7db4c854c` in `requirements.txt` and I still see the block number as `-1` in tests.

We're just running `starknet-devnet` without `--lite-mode` (I removed the line here https://github.com/smartcontractkit/chainlink-starknet/blob/f945756a5978dfc52ca099e8dd28edfc2dbdd50c/contracts/hardhat.config.ts#L34). Then we use `get_block_number()` in the contract:

https://github.com/smartcontractkit/chainlink-starknet/blob/f945756a5978dfc52ca099e8dd28edfc2dbdd50c/contracts/contracts/ocr2/aggregator.cairo#L318-L320

Then in a view function we return it: https://github.com/smartcontractkit/chainlink-starknet/blob/f945756a5978dfc52ca099e8dd28edfc2dbdd50c/contracts/contracts/ocr2/aggregator.cairo#L476

It's returned as `-1n` in our tests. (I added a `console.log(result)` here https://github.com/smartcontractkit/chainlink-starknet/blob/f945756a5978dfc52ca099e8dd28edfc2dbdd50c/contracts/test/ocr2/aggregator-test.ts#L146)
